### ISSUE TITLE
 inverse kinematics code

### ISSUE THREAD

**Issue by XiaXia009** [JayshKhan/5-1DOF_kinematics#1]
Hello, thank you very much for doing this.
I love you all. Inverse kinematics is bothering me

But the link you provided in the pdf cannot be accessed. :(

**Comment by JayshKhan** [comment]
Hi there! Thanks for reaching out about the broken link in the PDF.

You're absolutely right, the code structure has been updated since the PDF was created. The forward and inverse kinematics functions are now both implemented within the Kinematics class in the file https://github.com/JayshKhan/5-1DOF_kinematics/blob/main/code/kinematics/Kinematics.py

**Comment by JayshKhan** [comment]
Hi there! Thanks for reaching out about the broken link in the PDF.

You're absolutely right, the code structure has been updated since the PDF was created. The forward and inverse kinematics functions are now both implemented within the Kinematics class in the file https://github.com/JayshKhan/5-1DOF_kinematics/blob/main/code/kinematics/Kinematics.py
